#!/bin/sh -x

set -e

echo "Create Service DATABASES"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE DATABASE music;
EOSQL


echo "Create Music User"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "music" <<-EOSQL
CREATE ROLE ${SERVICE_MS_USER} WITH LOGIN;
ALTER USER ${SERVICE_MS_USER} WITH ENCRYPTED PASSWORD '${SERVICE_MS_PASSWORD}';

EOSQL


echo "Create Music User for Migration"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "music" <<-EOSQL
CREATE ROLE ${SERVICE_USER} WITH LOGIN;
ALTER USER ${SERVICE_USER} WITH ENCRYPTED PASSWORD '${SERVICE_PASSWORD}';

ALTER DATABASE music OWNER TO ${SERVICE_USER};
ALTER SCHEMA public OWNER TO ${SERVICE_USER};
EOSQL

